spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Munify;encrypt=true;trustServerCertificate=true
    username: maugallo
    password: TuPasswordFuerte123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none       # none / validate / update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
