spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  docker.compose:
      lifecycle-management: start_only

  flyway:
    enabled: false

google:
  maps:
    apiKey: ${GOOGLE_MAPS_API_KEY}
    places.baseUrl: https://places.googleapis.com/v1
    geocoding.baseUrl: https://maps.googleapis.com/maps/api/geocode

storage:
  endpoint: http://localhost:9000
  bucket: ${STORAGE_BUCKET}
  region: us-east-1
  accessKey: ${MINIO_ROOT_USER}
  secretKey: ${MINIO_ROOT_PASSWORD}
  putTtl: PT10M   # 10 minutos
  getTtl: PT5M   # 5 minutos
