spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Munify;encrypt=true;trustServerCertificate=true
    username: sa
    password: TuPasswordFuerte123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create       # none / validate / update / create / create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
